import { StyleSheet, Dimensions } from 'react-native';

const IMAGE_MARGIN = 1;
const NUM_COLUMNS = 3;
const HORIZONTAL_PADDING = 20;
const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
 container: {
   flex: 1,
   backgroundColor: '#F8FAFC',
 },
 header: {
   flexDirection: 'row',
   justifyContent: 'space-between',
   alignItems: 'center',
   paddingHorizontal: 20,
   paddingTop: 20,
   paddingBottom: 24,
 },
 title: {
   fontSize: 28,
   fontWeight: '700',
//    color: '#1E293B',
   fontFamily: 'Inter-Bold',
 },
 headerButtons: {
   flexDirection: 'row',
   gap: 12,
 },
 headerButton: {
   width: 44,
   height: 44,
   borderRadius: 22,
   backgroundColor: '#E0E7FF',
   alignItems: 'center',
   justifyContent: 'center',
 },
 emptyState: {
   flex: 1,
   alignItems: 'center',
   justifyContent: 'center',
   paddingHorizontal: 40,
 },
 emptyTitle: {
   fontSize: 24,
   fontWeight: '600',
   color: '#1E293B',
   fontFamily: 'Inter-SemiBold',
   marginTop: 20,
   marginBottom: 8,
 },
 emptyDescription: {
   fontSize: 16,
   color: '#64748B',
   textAlign: 'center',
   lineHeight: 24,
   fontFamily: 'Inter-Regular',
   marginBottom: 32,
 },
 addButton: {
   flexDirection: 'row',
   alignItems: 'center',
   backgroundColor: '#2563EB',
   paddingHorizontal: 24,
   paddingVertical: 12,
   borderRadius: 12,
   gap: 8,
 },
 addButtonText: {
   color: 'white',
   fontSize: 16,
   fontWeight: '600',
   fontFamily: 'Inter-SemiBold',
 },
 timeline: {
   flex: 1,
   paddingHorizontal: HORIZONTAL_PADDING,
 },
 memoryCard: {
   backgroundColor: 'white',
   borderRadius: 16,
   marginBottom: 24,
   overflow: 'hidden',
   shadowColor: '#000',
   shadowOffset: {
     width: 0,
     height: 2,
   },
   shadowOpacity: 0.1,
   shadowRadius: 8,
   elevation: 3,
 },
 memoryHeader: {
   padding: 16,
   paddingBottom: 12,
 },
 memoryDate: {
   flexDirection: 'row',
   alignItems: 'center',
   gap: 6,
   marginBottom: 8,
 },
 dateText: {
   fontSize: 14,
   color: '#64748B',
   fontFamily: 'Inter-Medium',
 },
 memoryLocation: {
   flexDirection: 'row',
   alignItems: 'center',
   gap: 6,
 },
 locationText: {
   fontSize: 12,
   color: '#64748B',
   fontFamily: 'Inter-Regular',
 },
 memoryImage: {
   width: '100%',
   height: 200,
   resizeMode: 'cover',
 },
 memoryContent: {
   padding: 16,
 },
 memoryTitle: {
   fontSize: 18,
   fontWeight: '600',
   color: '#1E293B',
   fontFamily: 'Inter-SemiBold',
   marginBottom: 8,
 },
 memoryDescription: {
   fontSize: 14,
   color: '#64748B',
   lineHeight: 20,
   fontFamily: 'Inter-Regular',
 },
 timelineDivider: {
   height: 1,
   backgroundColor: '#E2E8F0',
   marginHorizontal: 16,
 },
 modalOverlay: {
   flex: 1,
   backgroundColor: 'rgba(30,41,59,0.4)',
   justifyContent: 'center',
   alignItems: 'center',
   paddingHorizontal: 20,
 },
 modalContent: {
   width: '100%',
   maxWidth: 400,
   backgroundColor: 'white',
   borderRadius: 16,
   padding: 20,
   alignItems: 'stretch',
   shadowColor: '#000',
   shadowOffset: { width: 0, height: 2 },
   shadowOpacity: 0.15,
   shadowRadius: 8,
   elevation: 5,
   maxHeight: '83%',
 },
 modalTitle: {
   fontSize: 20,
   fontWeight: '700',
   color: '#1E293B',
   marginBottom: 16,
   textAlign: 'center',
   fontFamily: 'Inter-Bold',
 },
 modalImage: {
   width: '100%',
   height: 160,
   borderRadius: 12,
   marginBottom: 16,
   resizeMode: 'cover',
 },
 input: {
   borderWidth: 1,
   borderColor: '#E5E7EB',
   borderRadius: 8,
   padding: 12,
   fontSize: 16,
   marginBottom: 16,
   fontFamily: 'Inter-Regular',
   backgroundColor: '#F1F5F9',
 },
 inputLabel: {
   fontSize: 16,
   fontWeight: '600',
   color: '#1E293B',
   marginBottom: 8,
   fontFamily: 'Inter-SemiBold',
 },
 dropdownButton: {
   borderWidth: 1,
   borderColor: '#E5E7EB',
   borderRadius: 8,
   padding: 12,
   marginBottom: 16,
   backgroundColor: '#F1F5F9',
   flexDirection: 'row',
   justifyContent: 'space-between',
   alignItems: 'center',
 },
 dropdownText: {
   fontSize: 16,
   color: '#1E293B',
   fontFamily: 'Inter-Regular',
 },
 placeholderText: {
   color: '#9CA3AF',
 },
 modalButton: {
   backgroundColor: '#2563EB',
   paddingHorizontal: 24,
   paddingVertical: 12,
   borderRadius: 8,
   alignItems: 'center',
   minWidth: 80,
 },
 galleryGrid: {
   paddingTop: 16,
   paddingBottom: 16,
 },
 galleryGridImage: {
   width: (width - HORIZONTAL_PADDING * 2 - IMAGE_MARGIN * 2 * NUM_COLUMNS) / NUM_COLUMNS,
   height: (width - HORIZONTAL_PADDING * 2 - IMAGE_MARGIN * 2 * NUM_COLUMNS) / NUM_COLUMNS,
   borderRadius: 8,
   margin: IMAGE_MARGIN,
   backgroundColor: '#E5E7EB',
 },
 detailOverlay: {
   flex: 1,
   backgroundColor: 'rgba(30,41,59,0.8)',
   justifyContent: 'center',
   alignItems: 'center',
 },
 detailContent: {
   width: '90%',
   backgroundColor: 'white',
   borderRadius: 16,
   padding: 20,
   alignItems: 'center',
 },
 detailImage: {
   width: 280,
   height: 280,
   borderRadius: 16,
   marginBottom: 20,
   resizeMode: 'contain',
   backgroundColor: '#F1F5F9',
 },
 detailClose: {
   alignSelf: 'flex-end',
   marginBottom: 8,
 },
 fullScreenOverlay: {
   flex: 1,
   backgroundColor: '#FFFFFF',
   justifyContent: 'center',
   alignItems: 'center',
 },
 fullScreenClose: {
   position: 'absolute',
   top: 60,
   left: 20,
   zIndex: 1,
   width: 40,
   height: 40,
   borderRadius: 20,
   backgroundColor: 'rgba(0,0,0,0.1)',
   alignItems: 'center',
   justifyContent: 'center',
 },
 fullScreenImage: {
   width: '100%',
   height: '80%',
   resizeMode: 'contain',
 },
 fullScreenDescription: {
   position: 'absolute',
   bottom: 60,
   left: 20,
   right: 20,
   backgroundColor: 'white',
   borderRadius: 12,
   padding: 16,
 },
 fullScreenDescriptionText: {
   color: 'black',
   fontSize: 20,
   textAlign: 'center',
   fontFamily: 'Inter-Medium',
 },
 fullScreenDescriptionDate: {
   color: 'black',
   fontSize: 18,
   textAlign: 'center',
   marginBottom: 8,
   fontFamily: 'Inter-Medium',
 },
 fullScreenDelete: {
   position: 'absolute',
   top: 60,
   right: 20,
   zIndex: 1,
   width: 40,
   height: 40,
   borderRadius: 20,
   backgroundColor: 'rgba(239, 68, 68, 0.1)',
   alignItems: 'center',
   justifyContent: 'center',
 },
 presentationControls: {
   position: 'absolute',
   top: 60,
   right: 20,
   flexDirection: 'row',
   alignItems: 'center',
   gap: 12,
   zIndex: 1,
 },
 presentationButton: {
   backgroundColor: 'rgba(226, 62, 17, 0.9)',
   paddingHorizontal: 12,
   paddingVertical: 6,
   borderRadius: 16,
 },
 presentationButtonText: {
   color: 'white',
   fontSize: 14,
   fontWeight: '600',
 },
 presentationCounter: {
   color: '#000',
   fontSize: 14,
   fontWeight: '600',
   backgroundColor: 'rgba(255, 255, 255, 0.9)',
   paddingHorizontal: 8,
   paddingVertical: 4,
   borderRadius: 12,
 },
 musicButton: {
   width: 36,
   height: 36,
   borderRadius: 18,
   backgroundColor: 'rgba(255, 255, 255, 0.9)',
   alignItems: 'center',
   justifyContent: 'center',
   marginRight: 8,
 },
});


export default styles;
